<a href="https://colab.research.google.com/github/one-2730/ESSA-25-1/blob/Assignment/ESAA_OB_0321_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#9.2 가우시안 혼합 모델

기댓값-최대화(EM) 알고리즘
1. 샘플을 클러스터에 할당 (기댓값 단계)
2. 클러스터 업데이트 (최대화 단계)

In [1]:
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=1000, noise=0.05)

In [2]:
from sklearn.mixture import GaussianMixture

gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [3]:
gm.weights_

array([0.20740241, 0.21089304, 0.58170455])

In [4]:
gm.means_

array([[-0.73702597,  0.57086314],
       [ 1.72447541, -0.07355891],
       [ 0.49568552,  0.25364756]])

In [5]:
gm.covariances_

array([[[ 0.05632349,  0.06429227],
        [ 0.06429227,  0.08842464]],

       [[ 0.06140153,  0.06763802],
        [ 0.06763802,  0.09089094]],

       [[ 0.16137699, -0.09555277],
        [-0.09555277,  0.28362706]]])

In [6]:
gm.converged_

True

In [7]:
gm.n_iter_

14

In [8]:
gm.predict(X)

array([2, 0, 1, 2, 1, 0, 1, 1, 2, 2, 2, 1, 2, 0, 2, 1, 2, 1, 2, 2, 2, 0,
       2, 0, 0, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 2, 0, 1, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 0,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 2, 0, 2, 0, 0, 2, 2, 1, 1, 2, 1, 2,
       2, 2, 0, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 0, 2, 1, 2, 2,
       2, 2, 1, 2, 2, 0, 1, 1, 0, 2, 2, 1, 2, 0, 1, 2, 2, 2, 2, 0, 2, 2,
       2, 0, 2, 0, 2, 2, 2, 2, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 1, 2, 2, 0,
       2, 0, 2, 0, 2, 0, 0, 1, 2, 2, 2, 1, 2, 2, 1, 2, 0, 0, 0, 1, 2, 1,
       2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0,
       0, 2, 2, 2, 2, 2, 1, 2, 0, 2, 1, 2, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0,
       1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 2,
       2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 1,
       2, 2, 2, 1, 1, 2, 1, 0, 2, 2, 2, 2, 1, 0, 0, 1, 2, 2, 1, 0, 2, 0,
       2, 0, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2,

In [9]:
gm.predict_proba(X)

array([[5.59491539e-098, 1.24223942e-014, 1.00000000e+000],
       [9.99777444e-001, 5.83066800e-170, 2.22555797e-004],
       [1.90597671e-204, 9.99926216e-001, 7.37843784e-005],
       ...,
       [3.67346604e-072, 1.16043381e-026, 1.00000000e+000],
       [1.66462846e-166, 9.96176229e-001, 3.82377108e-003],
       [9.24528528e-032, 2.19875408e-061, 1.00000000e+000]])

가우시안 혼합 모델은 생성 모델이므로 모델에서 새로운 샘플을 만들 수 있음

In [10]:
X_new, y_new = gm.sample(6)

X_new

array([[-0.40175843,  1.07694565],
       [-0.79774836,  0.81873818],
       [ 1.61856603, -0.24478925],
       [ 0.60770571,  0.41597314],
       [ 0.86528821, -0.87159739],
       [-0.22229029,  2.14368934]])

In [11]:
y_new

array([0, 0, 1, 2, 2, 2])

주어진 위치에서 모델의 밀도 추정 가능. score_samples()메서드는 그 위치의 확률 밀도 함수의 로그를 예측

In [12]:
gm.score_samples(X)

array([-1.50386938e+00, -3.75923066e-01, -8.66750416e-01, -1.99095497e+00,
       -4.62276138e-01, -3.57188594e-01, -1.21088779e+00, -9.96171061e-01,
       -2.03570927e+00, -1.39447740e+00, -1.98537131e+00, -1.01079879e+00,
       -2.00944893e+00, -8.60254172e-01, -1.48076509e+00, -6.85230940e-01,
       -1.65147456e+00, -1.75850627e+00, -1.58031783e+00, -1.71783177e+00,
       -1.52383630e+00, -8.66834543e-01, -2.23048031e+00, -2.65208237e-01,
       -1.50523734e+00,  1.17535042e-02, -1.47932084e+00, -2.10913037e+00,
       -1.52880096e+00, -3.25286402e-01, -1.60704478e+00, -1.50980693e+00,
       -2.16180850e+00, -1.58761790e+00, -1.29479911e+00, -1.55404161e+00,
       -1.29677293e+00, -1.53630217e+00, -1.02980164e+00, -1.55573992e+00,
       -1.47508614e+00, -1.81055407e+00, -6.97913618e-02, -1.65687122e+00,
       -1.76347630e+00, -1.81542960e+00, -1.53131895e+00, -1.32077667e+00,
       -1.48766212e+00, -1.55168295e+00, -1.77402406e+00, -1.74170712e+00,
       -3.11390457e-01, -

##9.2.1 가우시안 혼합을 사용한 이상치 탐지


- 이상치 감지
  - 밀도가 낮은 지역에 있는 샘플을 이상치로 간주
: 밀도 임곗값을 지정해야 함
- 특이치 감지
  - 이상치로 오염되지 않은 데이터셋에서 훈련

In [13]:
import numpy as np

densities = gm.score_samples(X)
density_threshold = np.percentile(densities, 4)
anomalies = X[densities < density_threshold]

##9.2.2 클러스터 개수 선택하기

In [14]:
gm.bic(X)

np.float64(2749.1952089758356)

In [15]:
gm.aic(X)

np.float64(2665.763369233139)

##9.2.3 베이즈 가우시안 혼합 모델

In [16]:
from sklearn.mixture import BayesianGaussianMixture

bgm = BayesianGaussianMixture(n_components=10, n_init=10)
bgm.fit(X)

np.round(bgm.weights_, 2)

/usr/local/lib/python3.11/dist-packages/sklearn/mixture/_base.py:269: ConvergenceWarning: Best performing initialization did not converge. Try different init parameters, or increase max_iter, tol, or check for degenerate data.
  warnings.warn(


array([0.13, 0.13, 0.13, 0.11, 0.12, 0.17, 0.12, 0.09, 0.  , 0.  ])

##9.2.4 이상치 탐지와 특이치 탐지를 위한 다른 알고리즘

- PCA
- Fast_MCD
  - 혼합된 것이 아니라 하나의 가우시안 분포에서 생성되었다고 가정
- 아이솔레이션 포레스트
  - 고차원의 데이터셋에서 효율적인 알고리즘
  - 무작위로 생성한 결정 트리로 구성된 랜덤 포레스트를 만든 후 각 노드에서 특성을 랜덤하게 선택한 다음 랜덤한 임곗값을 골라 데이터셋을 둘로 나눔.
  - 모든 데이터셋이 다른 샘플과 나눠질 때까지한 후에 이상치를 탐지
  - 이상치는 일반적으로 적은 단계에서 걸러지는 경향이 있음. 이를 이용해 이상치를 탐지함
- LOF
  - 샘플 주위의 밀도와 이웃 주위의 밀도를 비교
- one-class SVM
  - 특이치 탐지에 더 적절하지만 대규모 데이터셋에서는 사용이 어려움